[project]
name = "recursive-transformer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.1.2",
    "setuptools>=75.1.0",
    "tiktoken>=0.8.0",
    "torch>=2.4.1",
    "triton>=3.0.0",
]
